export const fakeOpportunities = [
	{
		opportunityID: 10,
		title: "New Opportunity",
		probOfCompletion: 0.5,
		amount: 1000,
		dateCreated: "2024-06-04T21:17:59.394774",
		dateClosed: null,
		stage: 1,
		assignedTo: 7,
		user: {
			userID: 7,
			username: "findersam@gmail.com",
			roleID: 1,
			role: null,
		},
		pipelineStage: {
			stageID: 1,
			stageName: "Prospecting",
		},
		notes: "New Opportunity Notes",
	},
	{
		opportunityID: 9,
		title: "New Sales Opportunity",
		probOfCompletion: 0.25,
		amount: 4000,
		dateCreated: "2024-06-03T14:58:35.6",
		dateClosed: null,
		stage: 3,
		assignedTo: 1,
		user: {
			userID: 1,
			username: "john_doe",
			roleID: 1,
			role: null,
		},
		pipelineStage: {
			stageID: 3,
			stageName: "Negotiation",
		},
		notes: "Initial contact made",
	},
	{
		opportunityID: 2,
		title: "New Title",
		probOfCompletion: 0.75,
		amount: 5000,
		dateCreated: "2024-06-05T10:00:00",
		dateClosed: "2024-06-20T15:00:00",
		stage: 2,
		assignedTo: 3,
		user: {
			userID: 3,
			username: "alice_jones",
			roleID: 3,
			role: null,
		},
		pipelineStage: {
			stageID: 2,
			stageName: "Proposal",
		},
		notes: "Updated notes.",
	},
	{
		opportunityID: 1,
		title: "Opportunity A",
		probOfCompletion: 0.75,
		amount: 10000,
		dateCreated: "2023-01-01T10:00:00",
		dateClosed: null,
		stage: 1,
		assignedTo: 1,
		user: {
			userID: 1,
			username: "john_doe",
			roleID: 1,
			role: null,
		},
		pipelineStage: {
			stageID: 1,
			stageName: "Prospecting",
		},
		notes: "First contact made, waiting for response",
	},
	{
		opportunityID: 3,
		title: "Opportunity C",
		probOfCompletion: 0.25,
		amount: 2000,
		dateCreated: "2023-03-01T12:00:00",
		dateClosed: null,
		stage: 3,
		assignedTo: 3,
		user: {
			userID: 3,
			username: "alice_jones",
			roleID: 3,
			role: null,
		},
		pipelineStage: {
			stageID: 3,
			stageName: "Negotiation",
		},
		notes: "Proposal sent, awaiting feedback",
	},
	{
		opportunityID: 4,
		title: "Opportunity D",
		probOfCompletion: 0.8,
		amount: 15000,
		dateCreated: "2023-04-01T13:00:00",
		dateClosed: "2023-04-10T13:00:00",
		stage: 4,
		assignedTo: 4,
		user: {
			userID: 4,
			username: "bob_brown",
			roleID: 3,
			role: null,
		},
		pipelineStage: {
			stageID: 4,
			stageName: "Won",
		},
		notes: "Negotiation phase, close to agreement",
	},

	{
		opportunityID: 5,
		title: "Opportunity E",
		probOfCompletion: 0.6,
		amount: 7000,
		dateCreated: "2023-05-01T14:00:00",
		dateClosed: null,
		stage: 5,
		assignedTo: 2,
		user: {
			userID: 2,
			username: "jane_smith",
			roleID: 2,
			role: null,
		},
		pipelineStage: {
			stageID: 5,
			stageName: "Lost",
		},
		notes: "Positive response, expecting closure soon",
	},
	{
		opportunityID: 6,
		title: "string",
		probOfCompletion: 0.25,
		amount: 4000,
		dateCreated: "2024-06-03T14:58:35.6",
		dateClosed: null,
		stage: 3,
		assignedTo: 1,
		user: {
			userID: 1,
			username: "john_doe",
			roleID: 1,
			role: null,
		},
		pipelineStage: {
			stageID: 3,
			stageName: "Negotiation",
		},
		notes: "string",
	},
	{
		opportunityID: 7,
		title: "string",
		probOfCompletion: 0.25,
		amount: 4000,
		dateCreated: "2024-06-03T14:58:35.6",
		dateClosed: null,
		stage: 3,
		assignedTo: 1,
		user: {
			userID: 1,
			username: "john_doe",
			roleID: 1,
			role: null,
		},
		pipelineStage: {
			stageID: 3,
			stageName: "Negotiation",
		},
		notes: "string",
	},
	{
		opportunityID: 8,
		title: "string",
		probOfCompletion: 0.25,
		amount: 4000,
		dateCreated: "2024-06-03T14:58:35.6",
		dateClosed: null,
		stage: 3,
		assignedTo: 1,
		user: {
			userID: 1,
			username: "john_doe",
			roleID: 1,
			role: null,
		},
		pipelineStage: {
			stageID: 3,
			stageName: "Negotiation",
		},
		notes: "string",
	},
];
